# Generated by Django 2.1.15 on 2020-09-12 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('altitud', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=8)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('topico', models.CharField(max_length=255)),
                ('actividad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunion.Actividad')),
                ('lugar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunion.Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioReunion',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('num_estrellas', models.IntegerField()),
                ('comentario', models.TextField()),
                ('reunion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunion.Reunion')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
