# Generated by Django 2.1.15 on 2020-09-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='facultad',
            field=models.CharField(choices=[('FI', 'Facultad de Ingeniería'), ('FC', 'Facultad de Ciencias'), ('FCA', 'Facultad de Contaduría y Administración'), ('FO', 'Facultad de Odontología'), ('FA', 'Facultad de Arquitectura'), ('FAD', 'Facultad de Artes y Diseño'), ('FQ', 'Facultad de Química'), ('FD', 'Facultad de Derecho'), ('FCPS', 'Facultad de Ciencias Políticas y Sociales'), ('FM', 'Facultad de Medicina'), ('FE', 'Facultad de Economía'), ('FMVZ', 'Facultad de Medicina Veterinaria y Zootecnia'), ('FP', 'Facultad de Psicología'), ('FFL', 'Facultad de Filosofía y Letras')], max_length=1),
        ),
    ]
